---
github:
  # This deletes the GitHub PR branch after successfully merged into the release
  delete_branch_on_merge: true

merge_actions:
  - trigger_pipeline:habitat/build:
      ignore_labels:
        - "Expeditor: Skip Habitat"
        - "Expeditor: Skip All"

pipelines:
  - habitat/build:
      definition: .expeditor/build.habitat.yml

promote:
  channels:
    - unstable
    - stable

subscriptions:
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages
